Nome = input('Boas-vindas! Como você se chama? ')
n = int(input('Olá, {}! Você deseja ver a tabuada de qual número? '.format(Nome)))

print(' T A B U A D A')
print('{:=^15}'.format(''))
print('1 x {} = {:>5}'.format(n, n*1))
print('2 x {} = {:>5}'.format(n, n*2))
print('3 x {} = {:>5}'.format(n, n*3))
print('4 x {} = {:>5}'.format(n, n*4))
print('5 x {} = {:>5}'.format(n, n*5))
print('6 x {} = {:>5}'.format(n, n*6))
print('7 x {} = {:>5}'.format(n, n*7))
print('8 x {} = {:>5}'.format(n, n*8))
print('9 x {} = {:>5}'.format(n, n*9))
print('10 x {} = {:>4}'.format(n, n*10))